ASSIGNMENT-4


In [38]:
# PRACTICE
import numpy as np
arr_1d=np.array(["a","b","c"])
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_1d)
print(arr_2d)
type(arr_2d)
print(arr_1d.dtype)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d[0:1,0:2])
a=np.array([1,2,3,4,5])
a[3:5]=400
print(a)


['a' 'b' 'c']
[[1 2 3]
 [4 5 6]]
<U1
2
(2, 3)
[[1 2]]
[  1   2   3 400 400]


In [39]:
#QUESTION-1
import numpy as np
arr=np.array([2,4,6,8,10])
print("The original array is:",arr)
print("after adding 2 to each element:",arr+2)
print("after multiplying 3 with each element:",arr*3)
print("after dividing each element with 2:",arr/2)

The original array is: [ 2  4  6  8 10]
after adding 2 to each element: [ 4  6  8 10 12]
after multiplying 3 with each element: [ 6 12 18 24 30]
after dividing each element with 2: [1. 2. 3. 4. 5.]


In [40]:
#QUESTION-2
import numpy as np
arr=np.array([1,2,3,6,4,5])
print("(a) Flipped array:",np.flip(arr))
print("\n")
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
print("(b)First array is:",x)
count=np.bincount(x)
print("Frequency of each number(0 to 5):",count)
mostfreq=np.argmax(count)
print("No.having highest frequency:",mostfreq)
indices=np.where(x==mostfreq)[0]
print("All indexes where",mostfreq,"is present in array:",indices)
print("\n")
print("Second array is:",y)
count2=np.bincount(y)
print("Frequency of each number(0 to 4):",count2)
mostfreq2=np.argmax(count)
print("No.having highest frequency:",mostfreq2)
indices2=np.where(y==mostfreq2)[0]
print("All indexes where",mostfreq2,"is present in array:",indices2)

(a) Flipped array: [5 4 6 3 2 1]


(b)First array is: [1 2 3 4 5 1 2 1 1 1]
Frequency of each number(0 to 5): [0 5 2 1 1 1]
No.having highest frequency: 1
All indexes where 1 is present in array: [0 5 7 8 9]


Second array is: [1 1 1 2 3 4 2 4 3 3]
Frequency of each number(0 to 4): [0 3 2 3 2]
No.having highest frequency: 1
All indexes where 1 is present in array: [0 1 2]


In [41]:
#QUESTION-3
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)
print("Element at first row and second column:",arr[0,1])
print("Element at third row and first column:",arr[2,0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at first row and second column: 20
Element at third row and first column: 70


In [42]:
#QUESTION-4
import numpy as np
Sarv=np.linspace(10,100,25)
print("The array is:",Sarv)
print("Dimensions of array:",Sarv.ndim)
print("Shape of array:",Sarv.shape)
print("Size of array:",Sarv.size)
print("Data-type of elements:",Sarv.dtype)
print("Total bytes consumed:",Sarv.nbytes)
transpose=Sarv.reshape(25,1)
print("Transpose of array:",transpose)
transpose_T=Sarv.T
print("Transpose using T attribute:",transpose_T)
print("Does transpose and transpose_T give same result?",np.array_equal(transpose,transpose_T))

The array is: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of array: 1
Shape of array: (25,)
Size of array: 25
Data-type of elements: float64
Total bytes consumed: 200
Transpose of array: [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Does transpose and transpose_T give same result? False


In [44]:
#QUESTION-5
import numpy as np
ucs420_Sarv=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print("The array is:",ucs420_Sarv)
print("Mean of elements:",np.mean(ucs420_Sarv))
print("Median of elements:",np.median(ucs420_Sarv))
print("Maximum element is:",np.max(ucs420_Sarv))
print("Minimum element is:",np.min(ucs420_Sarv))
print("Unique element is:",np.unique(ucs420_Sarv))
reshaped_ucs420_Sarv=ucs420_Sarv.reshape(4,3)
print("Reshaped array:",reshaped_ucs420_Sarv)
resized_ucs420_Sarv=np.resize(ucs420_Sarv,(2,3))
print("Resized array:",resized_ucs420_Sarv)

The array is: [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean of elements: 43.333333333333336
Median of elements: 37.5
Maximum element is: 90
Minimum element is: 10
Unique element is: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array: [[10 20 30]
 [40 50 60]]
